// <auto-generated />
using Duallo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Duallo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Duallo.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Most powerful ARM-based chip",
                            Name = "M4"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The fastest growing smartphone on market",
                            Name = "Google Pixel 9"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The newest and the most convenient delivery ever",
                            Name = "Drone delivery"
                        });
                });

            modelBuilder.Entity("Duallo.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Motto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Motto = "Think different",
                            Name = "Apple's main Team",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Motto = "Don't be evil",
                            Name = "Google's main Team",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            Motto = "Work hard, Have fun, Make history",
                            Name = "Amazon's main Team",
                            ProjectId = 3
                        });
                });

            modelBuilder.Entity("Duallo.Models.Team", b =>
                {
                    b.HasOne("Duallo.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
